.TH "TypeLivre" 3 "Thu Nov 8 2018" "Version V1.0" "My Project 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeLivre
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBauteur\fP [200]"
.br
.ti -1c
.RI "char \fBtitre\fP [200]"
.br
.ti -1c
.RI "short \fBan\fP"
.br
.ti -1c
.RI "struct \fBTypeLivre\fP * \fBsuivant\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project 1 from the source code\&.
