main.c
typedef struct TypeLivre LIV
void savetexte(LIV *premier)
savetexte sauvegarde la bibliotheque
premier un pointeur sur LIV oik
References TypeLivre::auteur, TypeLivre::titre, TypeLivre::an, TypeLivre::suivant.
Referenced by main.
void affiche(LIV *premier)
affiche la fonction affiche permet de lister ma bibliothèque
premier un pointeur qui pointe sur le premier livre de ma bibliotéque auteur GBdate 181107 revu 181108
References TypeLivre::auteur, TypeLivre::titre, TypeLivre::an, TypeLivre::suivant.
Referenced by main.
void ajoute(char *titre, char *auteur, int an, LIV *premier)
References TypeLivre::auteur, TypeLivre::titre, TypeLivre::an, TypeLivre::suivant.
Referenced by main.
int main()
References TypeLivre::auteur, TypeLivre::titre, TypeLivre::an, TypeLivre::suivant, ajoute, affiche, savetexte.