.TH "TypeLivre" 3 "Jeudi 8 Novembre 2018" "Version v3" "projet_test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeLivre
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBauteur\fP [200]"
.br
.ti -1c
.RI "char \fBtitre\fP [200]"
.br
.ti -1c
.RI "short \fBan\fP"
.br
.ti -1c
.RI "struct \fBTypeLivre\fP * \fBsuivant\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "short an"

.SS "char auteur[200]"

.SS "struct \fBTypeLivre\fP* suivant"

.SS "char titre[200]"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour projet_test à partir du code source\&.
